/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-09 14:08:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chatView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/FinalYearProject/apache-tomcat-8.5.53/wtpwebapps/finalyearProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153381482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583672378186L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- https://www.youtube.com/watch?v=ABoCeLjY0Xo -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Chat View</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.min.css\"/>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\tfont-family: verdana;\r\n");
      out.write("}\r\n");
      out.write("#content, #result{\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tbox-shadow: 0 0 10px 0 #bbb;\r\n");
      out.write("\tmargin-botton: 30px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tline-height: 25px;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 240px;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("   \r\n");
      out.write("        $(\"#cancelBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t\tlocation.href = \"../board/list\";\t\r\n");
      out.write("\t\t});  \r\n");
      out.write("        \r\n");
      out.write("        $(\"#voiceBtn\").on(\"click\", function(){\r\n");
      out.write("        \tstartConverting();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\"#copyBtn\").on(\"click\", function(){\r\n");
      out.write("        \tcopyBtn();\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"container\">\t\r\n");
      out.write("\t<form name=\"chatForm\" method=\"post\" action=\"/chat/Chat\">\r\n");
      out.write("\t\t<label>From</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"user1\" id=\"user1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"/><br/>\r\n");
      out.write("\t\t<label>To</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"user2\" id=\"user2\" value=\"");
      out.print(request.getParameter("writer") );
      out.write("\" readonly=\"readonly\"/><br/>\r\n");
      out.write("\t    <label>Content</label>\r\n");
      out.write("\t    <input type=\"text\" name=\"content\" id=\"content\" placeholder=\"You can type or paste the voice content via Ctrl+V\"/>\r\n");
      out.write("\t    <br/>\r\n");
      out.write("\t\t<input class=\"btn btn-primary\" type=\"button\" id=\"voiceBtn\" value=\"Voice\" />\r\n");
      out.write("\t\t<input class=\"btn btn-secondary\" type=\"button\" id=\"copyBtn\" value=\"Copy and Paste\" />\t    \r\n");
      out.write("\t\t<div id=\"result\">\r\n");
      out.write("\t\t</div>\t  \r\n");
      out.write("\t    <br/>\r\n");
      out.write("\t    <input class=\"btn btn-success\" type=\"submit\" id=\"sendBtn\" value=\"Send\" />\r\n");
      out.write("\t    <input class=\"btn btn-danger\" type=\"button\" id=\"cancelBtn\" value=\"Exit\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar r = document.getElementById('result');\r\n");
      out.write("\t\tvar speechRecognizer = new webkitSpeechRecognition();\r\n");
      out.write("\t\tvar recognizing = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction startConverting(){\r\n");
      out.write("\t\t\tif('webkitSpeechRecognition' in window){\r\n");
      out.write("\t\t\t\tvar speechRecognizer = new webkitSpeechRecognition();\r\n");
      out.write("\t\t\t\trecognizing = true;\r\n");
      out.write("\t\t\t\tspeechRecognizer.continuous = true;\r\n");
      out.write("\t\t\t\tspeechRecognizer.interimResults = true;\r\n");
      out.write("\t\t\t\tspeechRecognizer.lang = 'en-UK';\r\n");
      out.write("\t\t\t\t//speechRecognizer.lang = 'ko-KR';\r\n");
      out.write("\t\t\t\tspeechRecognizer.start();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar finalTranscripts = '';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tspeechRecognizer.onresult = function(event){\r\n");
      out.write("\t\t\t\t\tvar interimTranscripts = '';\r\n");
      out.write("\t\t\t\t\tfor(var i=0; i < event.results.length; i++){\r\n");
      out.write("\t\t\t\t\t\tvar transcript = event.results[i][0].transcript;\r\n");
      out.write("\t\t\t\t\t\ttranscript.replace(\"\\n\",\"<br>\");\r\n");
      out.write("\t\t\t\t\t\tif(event.results[i].isFinal){\r\n");
      out.write("\t\t\t\t\t\t\tfinalTranscripts += transcript;\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tinterimTranscripts += transcript;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tr.innerHTML = finalTranscripts + '<span style=\"color:#999\">' + interimTranscripts + '</span>';\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tspeechRecognizer.onerror = function(event){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\tr.innerHTML = 'Error';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\t//https://www.google.com/intl/en/chrome/demos/speech.html\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction copyBtn(){\r\n");
      out.write("\t\t\tif(recognizing){\r\n");
      out.write("\t\t\t\trecognizing = false;\r\n");
      out.write("\t\t\t\tspeechRecognizer.stop();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert(\"Scroll the text. Press Control-C to copy text.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/chat/chatView.jsp(17,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("../resources/js/sockjs-0.3.4.js");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
