/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-06 14:36:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chatView2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/FinalYearProject/apache-tomcat-8.5.53/wtpwebapps/finalyearProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153381482000L));
    _jspx_dependants.put("jar:file:/C:/FinalYearProject/apache-tomcat-8.5.53/wtpwebapps/finalyearProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153381482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583672378186L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Chat View</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var ws;\r\n");
      out.write("\r\n");
      out.write("function connect() {\r\n");
      out.write("    var username = '");
      out.print(request.getParameter("sender"));
      out.write("';\r\n");
      out.write("    \r\n");
      out.write("    var host = document.location.host;\r\n");
      out.write("    var pathname = document.location.pathname;\r\n");
      out.write("    \r\n");
      out.write("    ws = new WebSocket(\"ws://\" + host  + pathname + username);\r\n");
      out.write("\r\n");
      out.write("    ws.onmessage = function(event) {\r\n");
      out.write("    var log = document.getElementById(\"log\");\r\n");
      out.write("        console.log(event.data);\r\n");
      out.write("        var message = JSON.parse(event.data);\r\n");
      out.write("        log.innerHTML += message.from.substring(9) + \" : \" + message.content + \"\\n\";\r\n");
      out.write("    };\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function send() {\r\n");
      out.write("    var content = document.getElementById(\"msg\").value;\r\n");
      out.write("    var json = JSON.stringify({\r\n");
      out.write("        \"content\":content\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    var data = {};\r\n");
      out.write("\tvar sender = '");
      out.print(request.getParameter("sender"));
      out.write("';\r\n");
      out.write("\tvar cno = '");
      out.print(request.getParameter("cno"));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tdata['cno'] = cno;\r\n");
      out.write("\tdata['user1'] = sender;\r\n");
      out.write("\tdata['content'] = document.getElementById(\"msg\").value;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({ \r\n");
      out.write("\t\turl : \"/chat/chatMessageWrite\",\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\tdata: data,\r\n");
      out.write("\t\tdataType : \"json\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tif(data){\r\n");
      out.write("\t\t\t\talert(\"Success\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\talert(\"Fail\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("    ws.send(json);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("   $(\"#cancelBtn\").on(\"click\", function(){\r\n");
      out.write("      \t\r\n");
      out.write("\t\tlocation.href = \"../board/list/\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t});    \r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 80%;\r\n");
      out.write("    background-color: #1f1f1f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("    width: 960px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    color: #d9d9d9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("    display: inline;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #f2791d;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    -moz-border-radius: 8px;\r\n");
      out.write("    -webkit-border-radius: 8px;\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover {\r\n");
      out.write("    background-color: #ffb15e;\r\n");
      out.write("}\r\n");
      out.write(".button a, a:visited, a:hover, a:active {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#addDevice {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 960px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#addDeviceForm {\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#addDeviceForm span {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    width: 960px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device {\r\n");
      out.write("    width: 180px;\r\n");
      out.write("    height: 110px;\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    padding: 16px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    -moz-border-radius: 8px;\r\n");
      out.write("    -webkit-border-radius: 8px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.off {\r\n");
      out.write("    background-color: #c8cccf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device span {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".deviceName {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".removeDevice {\r\n");
      out.write("    margin-top: 12px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Appliance {\r\n");
      out.write("    background-color: #5eb85e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Appliance a:hover {\r\n");
      out.write("    color: #a1ed82;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Electronics {   \r\n");
      out.write("    background-color: #0f90d1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Electronics a:hover {\r\n");
      out.write("    color: #4badd1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Lights {\r\n");
      out.write("    background-color: #c2a00c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Lights a:hover {\r\n");
      out.write("    color: #fad232;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Other {\r\n");
      out.write("    background-color: #db524d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device.Other a:hover {\r\n");
      out.write("    color: #ff907d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device a:visited, a:active, a:hover {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".device a:hover {\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"container\">\r\n");
      out.write("\t<table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                    <button type=\"button\" onclick=\"connect();\" >Connect</button>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <textarea readonly=\"readonly\" rows=\"10\" cols=\"80\" id=\"log\"></textarea>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"text\" size=\"51\" id=\"msg\" placeholder=\"Message\"/>\r\n");
      out.write("                    <button type=\"button\" id=\"sendBtn\" onclick=\"send();\" >Send</button>\r\n");
      out.write("                    <input type=\"button\" id=\"cancelBtn\" value=\"Exit\" />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
